In [7]:
import os
import pandas as pd
import numpy as np
from dotenv import load_dotenv
from supabase import create_client

load_dotenv("../../.env")

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

supabase = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

In [8]:
trials = supabase.table("trials").select("*").eq("trial_type", "training").execute().data
shake_reports = supabase.table("shake_reports").select("*").execute().data
morphology_profiles = supabase.table("morphology_profiles").select("*").execute().data

trials_df = pd.DataFrame(trials)
shake_df = pd.DataFrame(shake_reports)
morph_df = pd.DataFrame(morphology_profiles)

display(trials_df)
display(shake_df)
display(morph_df)

,id,trial_type,collection_id,weight,morphology_profile_id,smitski_name_id
0,2,training,1,42.8,2,2
1,3,training,2,38.5,3,3
2,4,training,3,37.6,4,4
3,5,training,4,38.7,5,5
4,6,training,5,46.0,6,6
5,1,training,1,45.6,1,1
6,7,training,6,38.2,7,7

    id  trial_id shake_position  movement_amount  loudness  sound_hardness
0   12         2      rotated_2                3         3             2.0
1   13         2        up_down                3         3             2.0
2   11         2      rotated_1                2         2             1.0
3   10         2  base_rotation                1         1             1.0
4    7         1      rotated_1                1         1             0.0
5   14         3  base_rotation                1         1             0.0
6   15         3      rotated_1                2         2             2.0
7   16         3      rotated_2                2         2             1.0
8   17         3        up_down                3         3             0.0
9   18         4  base_rotation                3         3             2.0
10  19         4      rotated_1                3         3             2.0
11  20         4      rotated_2                3         3             2.0
12  21         4        up_down                3         3             1.0
13  22         5  base_rotation                1         1             0.0
14  23         5      rotated_1                2         2             1.0
15  24         5      rotated_2                1         1             0.0
16  25         5        up_down                1         1             0.0
17  26         6  base_rotation                0         0             NaN
18  27         6      rotated_1                0         0             NaN
19  28         6      rotated_2                1         1             0.0
20  29         6        up_down                1         1             0.0
21   5         1  base_rotation                3         3             1.0
22   8         1      rotated_2                3         3             1.0
23   9         1        up_down                2         2             1.0
24  30         7  base_rotation                3         3             2.0
25  31         7      rotated_1                3         2             1.0
26  32         7      rotated_2                1         1             0.0
27  33         7        up_down                2         2             1.0

,id,is_symmetrical,smiski_size,total_prop_number,largest_prop_size,multi_body,elongation_profile,compactness,body_type,multi_body_is_joined,multi_body_has_smaller_body
0,1,False,standard,1,0.0,False,2,1,NaN,None,None
1,2,True,standard,0,NaN,False,1,1,NaN,None,None
2,3,False,standard,0,NaN,False,2,0,NaN,None,None
3,4,False,standard,0,NaN,False,1,1,normal,None,None
4,5,True,standard,0,NaN,False,1,2,normal,None,None
5,6,False,smaller,2,1.0,True,1,0,NaN,False,False
6,7,False,standard,0,NaN,False,1,1,NaN,None,None

In [9]:
trial_labels_df = trials_df.merge(
    morph_df,
    left_on="morphology_profile_id",
    right_on="id",
    suffixes=("_trial", "_morph")
)

display(trial_labels_df)

,id_trial,trial_type,collection_id,weight,morphology_profile_id,smitski_name_id,id_morph,is_symmetrical,smiski_size,total_prop_number,largest_prop_size,multi_body,elongation_profile,compactness,body_type,multi_body_is_joined,multi_body_has_smaller_body
0,2,training,1,42.8,2,2,2,True,standard,0,NaN,False,1,1,NaN,None,None
1,3,training,2,38.5,3,3,3,False,standard,0,NaN,False,2,0,NaN,None,None
2,4,training,3,37.6,4,4,4,False,standard,0,NaN,False,1,1,normal,None,None
3,5,training,4,38.7,5,5,5,True,standard,0,NaN,False,1,2,normal,None,None
4,6,training,5,46.0,6,6,6,False,smaller,2,1.0,True,1,0,NaN,False,False
5,1,training,1,45.6,1,1,1,False,standard,1,0.0,False,2,1,NaN,None,None
6,7,training,6,38.2,7,7,7,False,standard,0,NaN,False,1,1,NaN,None,None